/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExperienceLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'elite' : null };
export interface NotificationSubscription {
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Time,
}
export type NotificationType = { 'planUpdate' : null } |
  { 'newExercise' : null } |
  { 'workoutReminder' : null } |
  { 'challengeUpdate' : null };
export type SportFocus = { 'gym' : null } |
  { 'bodyweight' : null } |
  { 'trail' : null } |
  { 'hyrox' : null } |
  { 'general' : null } |
  { 'rehab' : null } |
  { 'running' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null } |
  { 'annualPro' : null };
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'experienceLevel' : ExperienceLevel,
  'heightCm' : number,
  'userId' : UserId,
  'createdAt' : Time,
  'subscriptionTier' : SubscriptionTier,
  'annualDiscountEligible' : boolean,
  'bodyweightKg' : number,
  'recommendedLoadPercent' : number,
  'updatedAt' : Time,
  'goals' : string,
  'weeklyTrainingFrequency' : bigint,
  'sportFocus' : SportFocus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<
    [number, number, ExperienceLevel, SportFocus, string, bigint],
    UserProfile
  >,
  'deleteProfile' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubscriptions' : ActorMethod<[], Array<NotificationSubscription>>,
  'getUserProfile' : ActorMethod<[UserId], UserProfile>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserTier' : ActorMethod<[UserId, SubscriptionTier], string>,
  'subscribe' : ActorMethod<[NotificationType], undefined>,
  'unsubscribeAll' : ActorMethod<[], undefined>,
  'updateProfile' : ActorMethod<
    [number, number, ExperienceLevel, SportFocus, string, bigint],
    UserProfile
  >,
  'upgradeToPro' : ActorMethod<[[] | [string], SubscriptionTier], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];