/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'elite' : IDL.Null,
});
export const SportFocus = IDL.Variant({
  'gym' : IDL.Null,
  'bodyweight' : IDL.Null,
  'trail' : IDL.Null,
  'hyrox' : IDL.Null,
  'general' : IDL.Null,
  'rehab' : IDL.Null,
  'running' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
  'annualPro' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'heightCm' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Time,
  'subscriptionTier' : SubscriptionTier,
  'annualDiscountEligible' : IDL.Bool,
  'bodyweightKg' : IDL.Float64,
  'recommendedLoadPercent' : IDL.Float64,
  'updatedAt' : Time,
  'goals' : IDL.Text,
  'weeklyTrainingFrequency' : IDL.Nat,
  'sportFocus' : SportFocus,
});
export const NotificationType = IDL.Variant({
  'planUpdate' : IDL.Null,
  'newExercise' : IDL.Null,
  'workoutReminder' : IDL.Null,
  'challengeUpdate' : IDL.Null,
});
export const NotificationSubscription = IDL.Record({
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        ExperienceLevel,
        SportFocus,
        IDL.Text,
        IDL.Nat,
      ],
      [UserProfile],
      [],
    ),
  'deleteProfile' : IDL.Func([], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(NotificationSubscription)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [UserProfile], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserTier' : IDL.Func([UserId, SubscriptionTier], [IDL.Text], []),
  'subscribe' : IDL.Func([NotificationType], [], []),
  'unsubscribeAll' : IDL.Func([], [], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Float64,
        IDL.Float64,
        ExperienceLevel,
        SportFocus,
        IDL.Text,
        IDL.Nat,
      ],
      [UserProfile],
      [],
    ),
  'upgradeToPro' : IDL.Func(
      [IDL.Opt(IDL.Text), SubscriptionTier],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'elite' : IDL.Null,
  });
  const SportFocus = IDL.Variant({
    'gym' : IDL.Null,
    'bodyweight' : IDL.Null,
    'trail' : IDL.Null,
    'hyrox' : IDL.Null,
    'general' : IDL.Null,
    'rehab' : IDL.Null,
    'running' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'annualPro' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'heightCm' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Time,
    'subscriptionTier' : SubscriptionTier,
    'annualDiscountEligible' : IDL.Bool,
    'bodyweightKg' : IDL.Float64,
    'recommendedLoadPercent' : IDL.Float64,
    'updatedAt' : Time,
    'goals' : IDL.Text,
    'weeklyTrainingFrequency' : IDL.Nat,
    'sportFocus' : SportFocus,
  });
  const NotificationType = IDL.Variant({
    'planUpdate' : IDL.Null,
    'newExercise' : IDL.Null,
    'workoutReminder' : IDL.Null,
    'challengeUpdate' : IDL.Null,
  });
  const NotificationSubscription = IDL.Record({
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          ExperienceLevel,
          SportFocus,
          IDL.Text,
          IDL.Nat,
        ],
        [UserProfile],
        [],
      ),
    'deleteProfile' : IDL.Func([], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(NotificationSubscription)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [UserProfile], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserTier' : IDL.Func([UserId, SubscriptionTier], [IDL.Text], []),
    'subscribe' : IDL.Func([NotificationType], [], []),
    'unsubscribeAll' : IDL.Func([], [], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Float64,
          IDL.Float64,
          ExperienceLevel,
          SportFocus,
          IDL.Text,
          IDL.Nat,
        ],
        [UserProfile],
        [],
      ),
    'upgradeToPro' : IDL.Func(
        [IDL.Opt(IDL.Text), SubscriptionTier],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };