/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Time = bigint;
export interface NotificationSubscription {
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Time;
}
export interface UserProfile {
    experienceLevel: ExperienceLevel;
    heightCm: number;
    userId: UserId;
    createdAt: Time;
    subscriptionTier: SubscriptionTier;
    annualDiscountEligible: boolean;
    bodyweightKg: number;
    recommendedLoadPercent: number;
    updatedAt: Time;
    goals: string;
    weeklyTrainingFrequency: bigint;
    sportFocus: SportFocus;
}
export enum ExperienceLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    elite = "elite"
}
export enum NotificationType {
    planUpdate = "planUpdate",
    newExercise = "newExercise",
    workoutReminder = "workoutReminder",
    challengeUpdate = "challengeUpdate"
}
export enum SportFocus {
    gym = "gym",
    bodyweight = "bodyweight",
    trail = "trail",
    hyrox = "hyrox",
    general = "general",
    rehab = "rehab",
    running = "running"
}
export enum SubscriptionTier {
    pro = "pro",
    free = "free",
    annualPro = "annualPro"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(bodyweightKg: number, heightCm: number, experienceLevel: ExperienceLevel, sportFocus: SportFocus, goals: string, weeklyTrainingFrequency: bigint): Promise<UserProfile>;
    deleteProfile(): Promise<void>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSubscriptions(): Promise<Array<NotificationSubscription>>;
    getUserProfile(userId: UserId): Promise<UserProfile>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserTier(userId: UserId, tier: SubscriptionTier): Promise<string>;
    subscribe(notificationType: NotificationType): Promise<void>;
    unsubscribeAll(): Promise<void>;
    updateProfile(bodyweightKg: number, heightCm: number, experienceLevel: ExperienceLevel, sportFocus: SportFocus, goals: string, weeklyTrainingFrequency: bigint): Promise<UserProfile>;
    upgradeToPro(discountCode: string | null, tier: SubscriptionTier): Promise<UserProfile>;
}
import type { ExperienceLevel as _ExperienceLevel, NotificationSubscription as _NotificationSubscription, NotificationType as _NotificationType, SportFocus as _SportFocus, SubscriptionTier as _SubscriptionTier, Time as _Time, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: number, arg1: number, arg2: ExperienceLevel, arg3: SportFocus, arg4: string, arg5: bigint): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, to_candid_ExperienceLevel_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SportFocus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, to_candid_ExperienceLevel_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SportFocus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptions(): Promise<Array<NotificationSubscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserTier(arg0: UserId, arg1: SubscriptionTier): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserTier(arg0, to_candid_SubscriptionTier_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserTier(arg0, to_candid_SubscriptionTier_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async subscribe(arg0: NotificationType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(to_candid_NotificationType_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(to_candid_NotificationType_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unsubscribeAll(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribeAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribeAll();
            return result;
        }
    }
    async updateProfile(arg0: number, arg1: number, arg2: ExperienceLevel, arg3: SportFocus, arg4: string, arg5: bigint): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_ExperienceLevel_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SportFocus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_ExperienceLevel_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SportFocus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async upgradeToPro(arg0: string | null, arg1: SubscriptionTier): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPro(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_SubscriptionTier_n26(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPro(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_SubscriptionTier_n26(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExperienceLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationSubscription_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationSubscription): NotificationSubscription {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SportFocus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SportFocus): SportFocus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Time;
}): {
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Time;
} {
    return {
        userId: value.userId,
        notificationType: from_candid_NotificationType_n22(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: _ExperienceLevel;
    heightCm: number;
    userId: _UserId;
    createdAt: _Time;
    subscriptionTier: _SubscriptionTier;
    annualDiscountEligible: boolean;
    bodyweightKg: number;
    recommendedLoadPercent: number;
    updatedAt: _Time;
    goals: string;
    weeklyTrainingFrequency: bigint;
    sportFocus: _SportFocus;
}): {
    experienceLevel: ExperienceLevel;
    heightCm: number;
    userId: UserId;
    createdAt: Time;
    subscriptionTier: SubscriptionTier;
    annualDiscountEligible: boolean;
    bodyweightKg: number;
    recommendedLoadPercent: number;
    updatedAt: Time;
    goals: string;
    weeklyTrainingFrequency: bigint;
    sportFocus: SportFocus;
} {
    return {
        experienceLevel: from_candid_ExperienceLevel_n9(_uploadFile, _downloadFile, value.experienceLevel),
        heightCm: value.heightCm,
        userId: value.userId,
        createdAt: value.createdAt,
        subscriptionTier: from_candid_SubscriptionTier_n11(_uploadFile, _downloadFile, value.subscriptionTier),
        annualDiscountEligible: value.annualDiscountEligible,
        bodyweightKg: value.bodyweightKg,
        recommendedLoadPercent: value.recommendedLoadPercent,
        updatedAt: value.updatedAt,
        goals: value.goals,
        weeklyTrainingFrequency: value.weeklyTrainingFrequency,
        sportFocus: from_candid_SportFocus_n13(_uploadFile, _downloadFile, value.sportFocus)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    elite: null;
}): ExperienceLevel {
    return "intermediate" in value ? ExperienceLevel.intermediate : "beginner" in value ? ExperienceLevel.beginner : "advanced" in value ? ExperienceLevel.advanced : "elite" in value ? ExperienceLevel.elite : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
} | {
    annualPro: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "free" in value ? SubscriptionTier.free : "annualPro" in value ? SubscriptionTier.annualPro : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gym: null;
} | {
    bodyweight: null;
} | {
    trail: null;
} | {
    hyrox: null;
} | {
    general: null;
} | {
    rehab: null;
} | {
    running: null;
}): SportFocus {
    return "gym" in value ? SportFocus.gym : "bodyweight" in value ? SportFocus.bodyweight : "trail" in value ? SportFocus.trail : "hyrox" in value ? SportFocus.hyrox : "general" in value ? SportFocus.general : "rehab" in value ? SportFocus.rehab : "running" in value ? SportFocus.running : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    planUpdate: null;
} | {
    newExercise: null;
} | {
    workoutReminder: null;
} | {
    challengeUpdate: null;
}): NotificationType {
    return "planUpdate" in value ? NotificationType.planUpdate : "newExercise" in value ? NotificationType.newExercise : "workoutReminder" in value ? NotificationType.workoutReminder : "challengeUpdate" in value ? NotificationType.challengeUpdate : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationSubscription>): Array<NotificationSubscription> {
    return value.map((x)=>from_candid_NotificationSubscription_n20(_uploadFile, _downloadFile, x));
}
function to_candid_ExperienceLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SportFocus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SportFocus): _SportFocus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel: ExperienceLevel;
    heightCm: number;
    userId: UserId;
    createdAt: Time;
    subscriptionTier: SubscriptionTier;
    annualDiscountEligible: boolean;
    bodyweightKg: number;
    recommendedLoadPercent: number;
    updatedAt: Time;
    goals: string;
    weeklyTrainingFrequency: bigint;
    sportFocus: SportFocus;
}): {
    experienceLevel: _ExperienceLevel;
    heightCm: number;
    userId: _UserId;
    createdAt: _Time;
    subscriptionTier: _SubscriptionTier;
    annualDiscountEligible: boolean;
    bodyweightKg: number;
    recommendedLoadPercent: number;
    updatedAt: _Time;
    goals: string;
    weeklyTrainingFrequency: bigint;
    sportFocus: _SportFocus;
} {
    return {
        experienceLevel: to_candid_ExperienceLevel_n3(_uploadFile, _downloadFile, value.experienceLevel),
        heightCm: value.heightCm,
        userId: value.userId,
        createdAt: value.createdAt,
        subscriptionTier: to_candid_SubscriptionTier_n26(_uploadFile, _downloadFile, value.subscriptionTier),
        annualDiscountEligible: value.annualDiscountEligible,
        bodyweightKg: value.bodyweightKg,
        recommendedLoadPercent: value.recommendedLoadPercent,
        updatedAt: value.updatedAt,
        goals: value.goals,
        weeklyTrainingFrequency: value.weeklyTrainingFrequency,
        sportFocus: to_candid_SportFocus_n5(_uploadFile, _downloadFile, value.sportFocus)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    free: null;
} | {
    annualPro: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value == SubscriptionTier.annualPro ? {
        annualPro: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    planUpdate: null;
} | {
    newExercise: null;
} | {
    workoutReminder: null;
} | {
    challengeUpdate: null;
} {
    return value == NotificationType.planUpdate ? {
        planUpdate: null
    } : value == NotificationType.newExercise ? {
        newExercise: null
    } : value == NotificationType.workoutReminder ? {
        workoutReminder: null
    } : value == NotificationType.challengeUpdate ? {
        challengeUpdate: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    elite: null;
} {
    return value == ExperienceLevel.intermediate ? {
        intermediate: null
    } : value == ExperienceLevel.beginner ? {
        beginner: null
    } : value == ExperienceLevel.advanced ? {
        advanced: null
    } : value == ExperienceLevel.elite ? {
        elite: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SportFocus): {
    gym: null;
} | {
    bodyweight: null;
} | {
    trail: null;
} | {
    hyrox: null;
} | {
    general: null;
} | {
    rehab: null;
} | {
    running: null;
} {
    return value == SportFocus.gym ? {
        gym: null
    } : value == SportFocus.bodyweight ? {
        bodyweight: null
    } : value == SportFocus.trail ? {
        trail: null
    } : value == SportFocus.hyrox ? {
        hyrox: null
    } : value == SportFocus.general ? {
        general: null
    } : value == SportFocus.rehab ? {
        rehab: null
    } : value == SportFocus.running ? {
        running: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
